name: Jenkins Trigger

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        id: extract_branch
        run: |
          BRANCH_NAME=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.number }}" | jq -r '.head.ref')
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Trigger Jenkins Job
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}"
          JENKINS_USERNAME="${{ secrets.JENKINS_USERNAME }}"
          JENKINS_API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          RESPONSE_CODE=$(curl -X POST -u "$JENKINS_USERNAME:$JENKINS_API_TOKEN" -o /dev/null -w "%{http_code}" "https://builds.gbif.org/job/ipt-pr/buildWithParameters?token=github-token-test&BRANCH_NAME=$BRANCH_NAME")

          if [ "$RESPONSE_CODE" -ne 201 ]; then
            echo "Failed to trigger Jenkins job. HTTP Response Code: $RESPONSE_CODE"
            exit 1
          fi

      - name: Set Status Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub API to set status
          status="success" # or "failure" based on your checks
          curl -s -X POST "https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${{ github.sha }}" \
               -H "Authorization: token $GITHUB_TOKEN" \
               -d "{
                \"state\": \"$status\",
                \"target_url\": \"https://your-ci-cd-url\",
                \"description\": \"Your check description\",
                \"context\": \"your-check-name\"
             }"

